language: java

jdk:
  - openjdk12

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

notifications:
  email:
    recipients:
      - jaeyeonling@gmail.com