version: '3'

services:
  mysql:
    image: mysql:$MYSQL_VERSION
    container_name: tiny-api-server-mysql-$MYSQL_VERSION
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=tiny
      - MYSQL_ROOT_HOST=127.0.0.1
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 10s
      retries: 10

  elasticsearch:
    container_name: tiny-api-server-elasticsearch-$ELK_VERSION
    build:
      context: docker/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    container_name: tiny-api-server-logstash-$ELK_VERSION
    build:
      context: docker/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: tiny-api-server-kibana-$ELK_VERSION
    build:
      context: docker/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  prometheus:
    container_name: tiny-api-server-prometheus-$PROMETHEUS_VERSION
    image: prom/prometheus:$PROMETHEUS_VERSION
    volumes:
      - ./docker/micrometer/config/prometheus.yml:/usr/share/micrometer/config/prometheus.yml:ro
    ports:
      - "9090:9090"

networks:
  elk:
    driver: bridge